services:

  # --- AQUÍ OCURRE LA MAGIA ---
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: denodo_user
      POSTGRES_PASSWORD: denodo_password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U denodo_user -d my_database"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      ai-sdk-net:
        ipv4_address: 172.20.0.2
    restart: unless-stopped

  vdp:
    image: harbor.open.denodo.com/denodo-express/denodo-platform:latest
    container_name: vdp
    hostname: vdp
    platform: linux/amd64
    ports:
      - "9090:9090"
      - "9999:9999"
      - "9994:9994"
    volumes:
      - ./config/denodo.lic:/opt/denodo/conf/denodo.lic:ro
      - csv_data:/opt/denodo/csv-data
    command: --vdpserver --datacatalog --designstudio
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      ai-sdk-net:
        ipv4_address: 172.20.0.3
    restart: unless-stopped

  ai-sdk:
    image: harbor.open.denodo.com/denodo-express/ai-sdk:latest
    container_name: ai-sdk
    platform: linux/amd64
    ports:
      - "8008:8008"
      - "9992:9992"
    volumes:
      - ./config/chatbot_config.env:/opt/ai-sdk/sample_chatbot/chatbot_config.env
      - ./config/sdk_config.env:/opt/ai-sdk/api/utils/sdk_config.env
    depends_on:
      - vdp
    command: bash -c "python run.py both --host vdp --no-logs"
    networks:
      ai-sdk-net:
        ipv4_address: 172.20.0.4
    restart: on-failure

volumes:
  postgres_data:
  csv_data:

networks:
  ai-sdk-net:
    name: ai-sdk-docker
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1